platform :ios, '11.0'

target 'SSFree' do
  use_frameworks!
  
  pod 'lottie-ios'
  
end

target 'PacketTunnel' do
  use_frameworks!

end

target 'SSWidget' do
  use_frameworks!
  
  pod 'TrafficPolice'

end
